version: "3"
services:
  eventservice:
    build:
      context: . #Dir for Compose to build

    # Portmapping
    ports:
      - "8000:8000"
      
    volumes: 
    # Copy changes to the image in real-time.
      - .:/eventservice
    # RUN
    command: sh -c "python ./eventservice/manage.py runserver 0.0.0.0:8000" 