version: "3"
services:
  eventservice:
    build:
      context: . #Dir for Compose to build

    # Portmapping
    ports:
      - "80:80"
      
    volumes: 
    # Copy changes to the image in real-time.
      - .:/eventservice